name: "Annotate Requirements"
description: "Annotates the requirements.txt file using the Score API"
runs:
  using: "node20"
  main: "dist/index.mjs"
inputs:
  ecosystem:
    description: "The package manager ecosystem to annotate. Currently supports 'pip', 'conda' 'npm'."
    required: true
  annotate-diff-only:
    description: "Set to true to annotate only modified lines in a PR."
    required: false
    default: "false"
  pip-requirements:
    description: "Path to the requirements.txt file to annotate."
    required: false
    default: "requirements.txt"
  # verbose:
  #   description: "Set to true to enable detailed logging."
  #   required: false
  #   default: "false"
