name: "Annotate Requirements"
description: "Annotates the requirements.txt file using the Score API"
runs:
  using: "node20"
  main: "dist/index.mjs"
inputs:
  diff-only:
    description: "Set to true to annotate only modified lines in a PR."
    required: false
    default: "false"
  requirements-txt:
    description: "Path to a requirements.txt file"
    required: false
  pyproject-toml:
    description: "Path to a pyproject.toml file"
    required: false
  package-json:
    description: "Path to a package.json file"
    required: false
