name: Test CLI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: test pyproject
        uses: ./
        with:
          pyproject-toml: test-files/pyproject.toml
          requirements-txt: false
          package-json: false

      - name: test requirements
        uses: ./
        with:
          requirements-txt: test-files/requirements.txt
          pyproject-toml: false
          package-json: false

      - name: test package.json
        uses: ./
        with:
          package-json: package.json
          pyproject-toml: false
          requirements-txt: false

      - name: test diff only package.json
        uses: ./
        with:
          diff-only: true
          package-json: package.json
          pyproject-toml: false
          requirements-txt: false

      # - name: Run Conda CLI
      #   run: |
      #     env INPUT_PACKAGE-ECOSYSTEM=conda INPUT_ANNOTATE-MODIFIED-ONLY=true node dist/index.cjs
