name: Test CLI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          pyproject-toml: test-files/pyproject.toml
          requirements-txt: false
          packagepackage-json: false

      - uses: ./
        with:
          requirements-txt: test-files/requirements.txt
          pyproject-toml: false
          packagepackage-json: false

      - uses: ./
        with:
          packagepackage-json: package.json
          pyproject-toml: false
          requirements-txt: false

      # - name: Run Conda CLI
      #   run: |
      #     env INPUT_PACKAGE-ECOSYSTEM=conda INPUT_ANNOTATE-MODIFIED-ONLY=true node dist/index.cjs
